<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Analyzer.Testing" />
    <PackageReference Include="TUnit.Engine" />
    <PackageReference Include="TUnit.Mocks" />
    <PackageReference Include="Verify" />
    <PackageReference Include="Verify.TUnit" />
    <ProjectReference Include="..\Melville.IntersectionTypes\Melville.IntersectionTypes.csproj" />
  </ItemGroup>
	
	<PropertyGroup>
		<Verify_SponsorshipExemption>OpenSource</Verify_SponsorshipExemption>
		<Verify_SponsorshipExemptionUntil>2027-09</Verify_SponsorshipExemptionUntil>
	</PropertyGroup>
</Project>
