<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="FluentAssertions" Version="[7.0.0]" />
    <PackageVersion Include="TUnit.Engine" Version="1.67.0" />
    <PackageVersion Include="TUnit.Mocks" Version="1.67.0" />
  </ItemGroup>
</Project>